### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by davidkrider** [jasonsturges/postgresql-dotnet-core#4]
I can add the connection string in appsettings.json, and the `services.AddDbContext<ApplicationDbContext>` in the ConfigurationServices in Startup.cs, but VisualStudio says that it doesn't  understand "ApplicationDbContext". It seems like it needs to be defined as another class or model?

**Comment by davidkrider** [comment]
Further reading reveals that ASP.NET Core with EF Core requires a class to define the DbContext so that it can be configured. None of the first 4 examples I found on Google relayed this fact. I guess it's assumed that a person would already know this, coming from the ASP.NET with EF world. I created a class in the Models directory, but I'm still not sure if there's a better location for this. You might want to put some guidance in your README for people like me, who are coming over to the ASP.NET(Core) world cold, from working with Rails for 15 years. ;-)

Models\ApplicationDbContext.cs:

`using Microsoft.EntityFrameworkCore;

namespace pmg2_tracker_core.Models
{

    public class ApplicationDbContext : DbContext
{
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        { }

        public DbSet<Assignment> Assignments { get; set; }
    }

}`

**Comment by jasonsturges** [comment]
@davidkrider Hi, thanks for the feedback.

DbContext is confusing, especially in that you can create any arbitrary number of them; or, reuse identity contexts - depends on what pattern you want to follow.

These projects were created as I found it needlessly complex to incorporate different database providers, especially MySQL.  I wanted a template that someone could clone depth 1 to start a project, really less tutorial oriented.  That said, you have to rely on the identity models to even test whether these work - there's no base example model other than user management.

This week I intend on updating all these projects to .NET Core 2.2, Visual Studio 2019.

Let me think about adding an example model.

**Comment by jasonsturges** [comment]
@davidkrider Good example project that isolates context to a Infrastructure library is:
https://github.com/dotnet-architecture/eShopOnWeb

You can see multiple contexts defined, such as:
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/CatalogContext.cs

DbContexts are loaded in ASP.NET Core Startup; or, can be loaded simply as:

```
var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>()
    .UseMySql(configuration.GetConnectionString("DefaultConnection"));
var context = new MyDbContext(optionsBuilder.Options);
context.Database.EnsureCreated();
```

**Comment by davidkrider** [comment]
If I post your code into Startup.cs, I get the same problem as before: "The type or namespace name 'MyDbContext' could not be found", and the top suggestion from Intellisense is that I need to generate a class.

**Comment by jasonsturges** [comment]
You can create any number of concrete custom contexts that inherit from `DbContext`.

In the EShopOnWeb example I cited, you can see their `CatalogContext`; otherwise, ASP.NET scaffolding produces an `ApplicationDbContext` for you by default.

Is this a public project here at GitHub?

**Comment by davidkrider** [comment]
I'm on ASP.NET Core, and I wonder if that's the difference. (And, no, no code for this on GitHub. Certain people would freak out, even when I'm just trying to attach a database at this point!)

**Comment by jasonsturges** [comment]
@davidkrider This is .NET Core - I'm running on Mac OS.  

Sounds like entry into the Microsoft stack is causing some friction, which is easily understandable.  It's pretty cool, high performance, and I find constructs of C# satisfying; but the platform can be interpreted as strict with some obscure patterns.

It's an exciting time for Microsoft technologies, going open source and cross platform.

My perspective is probably inverse to yours, where I find Rails frustrating; however, potentially similar in that I now lean towards .NET Core over JavaScript / Node.js.

Hopefully isolating some code will help diagnose how you're handling data.  Good luck.
