### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by gauravgupta98** [jasonsturges/postgresql-dotnet-core#9]
Can we do the following upgrades -

- .NET Core 3.1 to .NET 5.
- Support for Authentication using JWT
- C# 9

**Comment by jasonsturges** [comment]
@gauravgupta98 Hi, that's exciting.  I'll look into that.

Presumably run the wizard and select JWT authentication, and just follow the relevant steps in the README, but I'll try to update this template when I get a chance.
